title:            Blue Mountain Bookstore
tagline:          An independent used bookstore at the corner of Main &amp; Center in downtown Union, Oregon.
canonical: http://bluemountainbookstore.com

# Owner/author information
owner:
  name:           Todd Howitt
  avatar:         todo
  bio:            "Proprietor"
  email:          todd@bluemountainbookstore.com
  twitter:        bluemtnbooks 
  facebook:       bluemtnbookstore
  github:         bluemountainbookstore
  location:       "Union, OR"

business:
  name:           Blue Mountain Bookstore

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

JB:
  comments:
    provider: facebook
    disqus:
      short_name: jekyllbootstrap
    livefyre:
      site_id: 123
    intensedebate:
      account: 123abc
    facebook:
      appid: 1593142297566173
      num_posts: 5
      width: 100%
      colorscheme: light

  # Settings for sharing 
  # Sharing is for things like tweet, plusone, hn upvotes, like, linkedin
  # Add a tweet button 		=> provider : tweet
  # Add a like button 		=> provider : like (you also need a facebook appid)
  # Add a plus one button 	=> provider : plusone
  # Add a HN button 		=> provider : hn
  # Add them all (i.e. hn + tweet + plusone + like) => provider : all
  # Set 'provider' to the sharing provider you want to use.
  # Set 'provider' to false to turn sharing off globally.
  #
  sharing :
    provider : all
    twitter :
      size :
      via : bluemtnbooks
      count :
    facebook :
      appid : 1593142297566173
      layout : button_count
      font :
      faces : false
      width : 90
    googleplus :
      size : medium
      width :
      annotation : bubble

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Contact
    url: /contact

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/bluemountainbookstore/bluemountainbookstore.github.io/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
